# -*- coding: utf-8 -*-
"""calculadora_inteligente.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1of5N9WMPIWzBS_KJ4v2Y8vqANrC2ESbw

'''
#Calculadora Inteligente

##### Nome do script: calculadora_inteligente.py
#####Autor: Ana Paula Antonio de Oliveira
#####Data de criação: 21/02/2025
#####Descrição: Esta calculadora foi desenvolvida para calcular o ponto de equilíbrio de uma empresa de cadernos artesanais e gerar um relatório básico.
#####Versão: 1.0
#####Requisitos: Python 3

'''

# Custos Fixos
"""

aluguel = float(input('digite o valor do Aluguel: '))
print(f" Aluguel = {aluguel} reais")

internet_tel = float(input('digite o valor da Internet e telefone: '))
print(f" Internet e telefone = {internet_tel} reais")

energia = float(input('digite o valor da energia: '))
print(f" Energia = {energia} reais")

agua = float(input('digite o valor da água: '))
print(f" Água = {agua} reais")

software = float(input('digite o valor do software: '))
print(f" Software = {software} reais")

marketing = float(input('digite o valor do marketing: '))
print(f" Marketing = {marketing} reais")

ecommerce = float(input('digite o valor do ecommerce: '))
print(f" Ecommerce = {ecommerce} reais")

contador = float(input('digite o valor do contador: '))
print(f" Contador = {contador} reais")

registro_marca = float(input('digite o valor do registro de marca: '))
print(f" Registro de marca = {registro_marca} reais")

embalagens = float(input('digite o valor das embalagens: '))
print(f" Embalagens = {embalagens} reais")

capital_giro = float(input('digite o valor do capital de giro: '))
print(f" Capital de giro = {capital_giro} reais")

total_fixos = aluguel + internet_tel + energia + agua + software + marketing + ecommerce + contador + registro_marca + embalagens + capital_giro
print(f" Total de custos fixos = {total_fixos} reais")

"""# Custos Variáveis"""

papel_kraft = float(input('digite o valor do papel kraft: '))
print(f" Papel kraft = {papel_kraft} reais")

folhas_internas = float(input('digite o valor das folhas internas: '))
print(f" Folhas internas = {folhas_internas} reais")

tinta = float(input('digite o valor da tinta: '))
print(f" Tinta = {tinta} reais")

linha_costura = float(input('digite o valor da linha de costura: '))
print(f" Linha de costura = {linha_costura} reais")

adesivos_tags = float(input('digite o valor dos acessórios e tags: '))
print(f" Acessórios e tags = {adesivos_tags} reais")

plastico_embalagem = float(input('digite o valor do plástico e embalagem: '))
print(f" Plástico e embalagem = {plastico_embalagem} reais")

frete = float(input('digite o valor do frete: '))
print(f" Frete = {frete} reais")

taxa_pagamento = float(input('digite o valor da taxa de pagamento: '))
print(f" Taxa de pagamento = {taxa_pagamento} reais")

total_variaveis = papel_kraft + folhas_internas + tinta + linha_costura + adesivos_tags + plastico_embalagem + frete + taxa_pagamento
print(f" Total de custos variáveis = {total_variaveis} reais")

"""# Preço de Venda Unitário"""

preço_unitario = float(input('digite o preço de venda unitário: '))
print(f" Preço de venda unitário = {preço_unitario} reais")

"""# Quantidade Mínima de Vendas"""

PE = int(total_fixos / (preço_unitario - total_variaveis))
print(f"O ponto de equilíbrio é de {PE} unidades por mês para cobrir os custos e não ter prejuízo.")
if PE % 2 == 0:
  print("O ponto de equilíbrio é par.")
else:
  print("O ponto de equilíbrio é ímpar.")

"""# Margem de Contribuição"""

margem_contribuiçao = ((preço_unitario - total_variaveis) / preço_unitario) * 100
print(f"A margem de contribuição é de {margem_contribuiçao}%.")

"""# Lucro a partir das Vendas Reais"""

qtde_vendida = int(input("Digite a quantidade vendida neste mês: "))
lucro_real = (qtde_vendida * margem_contribuiçao) - total_fixos

if lucro_real > 0:
  print(f"Parabéns! Seu lucro foi de R${lucro_real}.")
elif lucro_real < 0:
  print(f"Infelizmente, você teve um prejuízo de R$ {lucro_real}.")
else:
  print("Você atingiu o ponto de equilíbrio, sem lucro nem prejuízo.")

"""# Sugestões para Diminuir o Ponto de Equilíbrio"""

sugestoes = input("Escreva sim ou não para receber sugestões para diminuir o ponto de equilíbrio: ")
if sugestoes == "sim":
    print("Abaixo você poderá ver sugestões para diminuir o PE.")
elif sugestoes == "não":
  print("Obrigado por usar o programa!")
else:
    print("Opção inválida. Escolha entre 'sim' ou 'não'.")

#Pelos custos fixos
sugestao = ["fixos", "variáveis"]
sugestao_fixos = ["negociar aluguel ou optar por home office", "cortar despesas desnecessárias, como software pouco usado ou anúncios ineficientes", "compartilhar infraestrutura", "reduzir gastos com marketing pago e apostar no orgânico"]
sugestao_variaveis = ["comprar matéria-prima em maior quantidade", "negociar com fornecedores", "aprimorar a eficiência da produção", "evitar intermediários e comprar direto do fabricante"]

#Escolha das sugestões por tipo
escolha_dica = input("Entre fixos ou variáveis, digite sobre qual variável quer dicas: ")
if escolha_dica == "fixos":
  for dica in sugestao_fixos:
    print(dica)
elif escolha_dica == "variáveis":
  for dica in sugestao_variaveis:
    print(dica)
else:
  print("Opção inválida. Escolha entre 'fixos' ou 'variáveis'.")